server:
  port: 51024

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth_route
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth-api/**
        - id: user_route
          uri: lb://user-service
          predicates:
            - Path=/api/v1/user-api/**
          filters:
            - PrefixPath=/user
        - id: file_route
          uri: lb://file-service
          predicates:
            - Path=/api/v1/file-api/**
          filters:
            - PrefixPath=/file
        - id: account_route
          uri: lb://account-service
          predicates:
            - Path=/api/v1/account-api/**
          filters:
            - PrefixPath=/account
        - id: order_route
          uri: lb://order-service
          predicates:
            - Path=/api/v1/order-api/**
          filters:
            - PrefixPath=/order
        - id: workflow_route
          uri: lb://workflow-service
          predicates:
            - Path=/api/v1/workflow-api/**
          filters:
            - PrefixPath=/workflow
        - id: sys_route
          uri: lb://sys-service
          predicates:
            - Path=/api/v1/sys-api/**
          filters:
            - PrefixPath=/sys

zhou6:
  gateway:
    path-prefix: /hakunaMatata
    openapi:
      auth-url: http://localhost:53072/v3/api-docs
      user-url: http://localhost:52048/user/v3/api-docs
      file-url: http://localhost:52049/file/v3/api-docs
      account-url: http://localhost:52050/account/v3/api-docs
      order-url: http://localhost:52051/order/v3/api-docs
      workflow-url: http://localhost:52052/workflow/v3/api-docs
      sys-url: http://localhost:52053/sys/v3/api-docs

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    config-url: /hakunaMatata/v3/api-docs/swagger-config
    urls:
      - name: auth-service
        url: /hakunaMatata/auth/v3/api-docs
      - name: user-service
        url: /hakunaMatata/user/v3/api-docs
      - name: file-service
        url: /hakunaMatata/file/v3/api-docs
      - name: account-service
        url: /hakunaMatata/account/v3/api-docs
      - name: order-service
        url: /hakunaMatata/order/v3/api-docs
      - name: workflow-service
        url: /hakunaMatata/workflow/v3/api-docs
      - name: sys-service
        url: /hakunaMatata/sys/v3/api-docs
