
server:
  port: 52051
  servlet:
    context-path: /order

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://81.70.186.59:5432/postgres?currentSchema=zhou6
    username: postgres
    password: a741741.
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      validation-timeout: 5000
      idle-timeout: 300000
      max-lifetime: 1500000
      keepalive-time: 300000
  threads:
    virtual:
      enabled: true
  rabbitmq:
    host: 81.70.186.59
    port: 5672
    username: admin
    password: admin123
  cloud:
    openfeign:
      client:
        config:
          account-service:
            connect-timeout: 1000
            read-timeout: 2000

zhou6:
  order:
    timeout-minutes: 15
    timeout-batch-size: 100
    timeout-scan-delay-ms: 60000
    mq:
      exchange: zhou6.order.account
      settle-routing-key: zhou6.account.settle
      unfreeze-routing-key: zhou6.account.unfreeze
